# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch

branches:
  only:
    - master

environment:
  access_token:
    # EDIT the encrypted version of your GitHub access token
    secure: FzXhH4JfxcygaW/6H5Z83NX8UAPLM1S1YgIZtW8luv6v+ZFSFxhm85UZWq7RQDBp

image: Visual Studio 2019

test: off

init:
  - git config --global core.autocrlf true

install:

build_script:
  - ps: .\build.ps1 -target docs

on_success:
#  - ..\Wyam\wyam --output ..\output
