name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.805
    - name: Install Wyam
      run: dotnet tool install --tool-path . wyam.tool
#    - name: Build blog
#      run: ./wyam -r Docs -t Samson
    - name: Build Blog with Cake Action
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        # The name of the task to execute. Note that this argument must be supported by the script.
        target: CIBuild
        # The verbosity level with which to run the script. Valid values are: Quiet, Minimal, Normal, Verbose or Diagnostic.
        #verbosity: # optional, default is Normal
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: ${{ secrets.ACCESS_EMAIL }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: ./output
