name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Wyam
      run: dotnet tool install --tool-path . wyam.tool
    - name: Build blog
      run: ./wyam -r Docs -t Samson
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: ${{ secrets.ACCESS_EMAIL }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: ./output
